_target_: watchmal.model.resnet_multiring_v2style.ResNetMultiRingV2Style
num_input_channels: 41
conv_pad_mode: circular
num_rings: 2
channels_per_ring: 7
slot_embed_dim: 32
num_output_channels: 7
group_norm: false
