_target_: watchmal.engine.regression_multiring_v3.MultiRingRegressionEngineV3
num_rings: 2
huber_delta: 0.1
aux_loss_weight: 0.3
vote_loss_weight: 0.5
target_scale_factor:
  positions: 1
  directions: 0.01
  energies: 1
