_target_: watchmal.engine.regression_multiring.MultiRingRegressionEngine
target_key:
  - positions
  - angles
  - energies
num_rings: 2
huber_delta: 0.1
target_scale_factor:
  positions: 1
  directions: 0.01
  energies: 1
