defaults:
    - wcte_defaults_pointnet
    - engine: regression
    - override loss@tasks.train.loss: huber
    - override loss@tasks.evaluate.loss: huber
    - _self_
engine:
  target_key:
    - positions
    - directions
    - energies
  target_scale_factor:
    positions: 1
    directions: 0.01
    energies: 1
model:
  num_output_channels: 7

